# Generated by Django 5.1.7 on 2025-04-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_all_day',
            field=models.BooleanField(default=False),
        ),
    ]
