# Generated by Django 5.1.4 on 2025-05-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecomment',
            name='display_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
