# Generated by Django 5.1.7 on 2025-04-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_memo_created_at_memo_image_url_memo_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='memo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memo_images/'),
        ),
    ]
