# Generated by Django 5.1.7 on 2025-04-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_memo_image_url_memo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='color',
            field=models.IntegerField(blank=True, choices=[(1, 'レッド'), (2, 'ブルー'), (3, 'イエロー'), (4, 'グリーン'), (5, 'ピンク'), (6, 'パープル'), (7, 'オレンジ')], null=True),
        ),
    ]
