# Generated by Django 5.1.7 on 2025-04-17 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_family_customuser_family_invite_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_title', models.CharField(max_length=100)),
                ('schedule_memo', models.CharField(blank=True, max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='schedule_images/')),
                ('color', models.IntegerField(choices=[(1, '#FF0000'), (2, '#0000FF'), (3, '#FFFF00'), (4, '#00FF00'), (5, '#F08080'), (6, '#800080'), (7, '#F57F33')], default=1)),
                ('repeat_type', models.IntegerField(choices=[(0, 'なし'), (1, '毎日'), (2, '毎週'), (3, '毎月')], default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
