# Generated by Django 5.1.7 on 2025-05-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_schedulecommentread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulecomment',
            name='comment_status',
        ),
    ]
