# Generated by Django 5.1.7 on 2025-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_schedulecomment_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
