# Generated by Django 5.1.7 on 2025-05-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_schedule_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecommentread',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
