# Generated by Django 5.1.7 on 2025-05-09 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_schedulecommentread_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecommentread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulecommentread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
