# Generated by Django 5.1.7 on 2025-05-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_schedulecommentread_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_relay_generated',
            field=models.BooleanField(default=False),
        ),
    ]
