# Generated by Django 5.1.7 on 2025-05-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_schedule_is_relay_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='is_relay_generated',
            new_name='is_relay_created',
        ),
    ]
